### ISSUE TITLE
ceate a corpus of existing coviho publications and create a data set deposit in coviho-Zenodo community

### ISSUE THREAD

**Issue by myrmoteras** [bat-literature/bat-literature.github.io#10]
create a corpus of the existing 543 articles in [coviho](https://zenodo.org/communities/coviho/records?q=&l=list&p=1&s=10&sort=newest) and deposit as data set in coviho. This should also include a bibliography including the zenodo deposition ID

Notify @myrmoteras when done

**Comment by jhpoelen** [comment]
Great idea to make mobilize the CoViHo corpus similarly to TaxoDros and BatLit. This does seem to be beyond the scope of batlit. Is there a place you keep track of the CoViHo issues?

**Comment by jhpoelen** [comment]
closing stale issue. Please contact batlit curator @ajacsherman if you'd like to pursue this.
