### ISSUE TITLE
assure that no duplicates are created with existing Zenodo/coviho/BLR deposits

### ISSUE THREAD

**Issue by myrmoteras** [bat-literature/bat-literature.github.io#11]
before we upload Aja's PDFS to zenodo, we need to check, whether the articles are already deposited in Zenodo.

A list of 500 articles in coviho are probably available from https://github.com/bat-literature/bat-literature.github.io/issues/10

a list of articles in BLR is available from here https://tb.plazi.org/GgServer/srsStats/stats?outputFields=pubLnk.articleDoi+pubLnk.articleZenodoDepId+tax.orderEpithet&groupingFields=pubLnk.articleDoi+pubLnk.articleZenodoDepId+tax.orderEpithet&FP-tax.orderEpithet=Chiroptera&format=HTML 

or in TSV 

https://tb.plazi.org/GgServer/srsStats/stats?outputFields=pubLnk.articleDoi+pubLnk.articleZenodoDepId+tax.orderEpithet&groupingFields=pubLnk.articleDoi+pubLnk.articleZenodoDepId+tax.orderEpithet&FP-tax.orderEpithet=Chiroptera&format=TSV

query in overall Zenodo
https://zenodo.org/communities/biosyslit/records?q=Chiroptera&f=resource_type%3Apublication%2Binner%3Apublication-article&l=list&p=1&s=10&sort=bestmatch

**Comment by jhpoelen** [comment]
covered in https://batlit.org/#deduplication-workflow .
