### ISSUE TITLE
add details for contributions

### ISSUE THREAD

**Issue by arw36** [bat-literature/bat-literature.github.io#38]
no guidance on contribution and minima required. 

https://batlit.org/#contributing 

unclear if the red star in Zenodo upload process is required?

**Comment by jhpoelen** [comment]
Thanks for sharing. 

currently, the process of submission is to:

1. contact curator of BatLit (@ajacsherman)
2. share pdfs 

Then, @ajacsherman follows the curatorial process https://batlit.org/#curation-workflow to include the proposed pdfs into the next batlit version.

**Comment by jhpoelen** [comment]
@arw36 if you have some suggestions on how to improve the existing curation workflow, please bring this up. For now, I am closing this issue, because the curation workflow is documented at https://batlit.org/#curation-workflow .
