### ISSUE TITLE
malformed DOI "nri2939 [pii]\r10.1038/nri2939" found in Romani 2011 https://www.zotero.org/groups/5435545/bat_literature_project/items/2WK8GVE9

### ISSUE THREAD

**Issue by jhpoelen** [bat-literature/bat-literature.github.io#4]
see attached screenshot of https://www.zotero.org/groups/5435545/bat_literature_project/items/2WK8GVE9 shows invalid doi ```nri2939 [pii]\r10.1038/nri2939``` . Expected ```10.1038/nri2939```

![image](https://github.com/bat-literature/bat-literature.github.io/assets/1084872/07f81066-7ba1-4572-9a60-dc953095d467)

**Comment by ajacsherman** [comment]
This DOI should be "https://doi.org/10.1038/nri2939", but the link through Zotero still brings me to an original source.

**Comment by jhpoelen** [comment]
Hi @ajacsherman Thanks for confirming that the DOI is malformed. 

I suspect that the Zotero Web UI applies some magic to turn the malformed DOI into a resolvable DOI. 

Suggest to change the DOI to ```10.1038/nri2939``` to make the value consistent with other records. 

See e.g., https://www.zotero.org/groups/5435545/bat_literature_project/items/BEGC9EYF/item-details value ```10.3390/v8100270``` and attached value.

![image](https://github.com/bat-literature/bat-literature.github.io/assets/1084872/1271a0f5-d1ac-4f39-9bc8-d5ccf82f8356)

**Comment by ajacsherman** [comment]
Do you have an exhausted list of corrupt DOIs? I can correct them if you can send me that list.

**Comment by jhpoelen** [comment]
For a list, see https://github.com/bat-literature/bat-literature.github.io/issues/5 .

**Comment by jhpoelen** [comment]
Out of 2784 DOI, I found only 46 suspected malformed DOIs by checking whether the DOI started with ```10.``` as extracted from v0.2 with signature hash://md5/be692b93a8edde4c4269be9e7d4ec1d7 generated via

```bash
preston ls\
 --algo md5\
 --anchor hash://md5/be692b93a8edde4c4269be9e7d4ec1d7\
 --remote https://linker.bio\
 | grep hasVersion\
 | grep "items?"\
 | preston cat\
 | jq --raw-output .[].data.DOI\
 | grep -v null\
 | sort\
 | uniq\
 | grep -v -E "^10[.]"
````

are:

```
Artn 550\rDoi 10.1186/S13059-014-0550-8
arXiv:1505.02710
http://dx.doi.org/10.1038/s41467-018-06779-w
https://doi.org/10.1002/ajp.23240
https://doi.org/10.1002/ece3.4842
https://doi.org/10.1002/ece3.5150
https://doi.org/10.1002/pro.2541
https://doi.org/10.1002/rse2.195
https://doi.org/10.1002/(SICI)1099-145X(199907/08)10:4<311::AID-LDR362>3.0.CO;2-3
https://doi.org/ 10.1017/S0031182019000817
https://doi.org/10.1046/j.0141-6707.2000.00299.x
https://doi.org/10.1098/rsbl.2021.0427
https://doi.org/10.1111/1365-2435.13640
https://doi.org/10.1111/1365-2656.13166
https://doi.org/10.1111/1365-2664.13619
https://doi.org/10.1111/2041-210X.12172
https://doi.org/10.1111/conl.12389
https://doi.org/10.1111/conl.12715
https://doi.org/10.1111/eva.12514
https://doi.org/10.1111/geb.13045
https://doi.org/10.1111/j.1365-2664.2005.01049.x
https://doi.org/10.1111/j.1461-0248.2010.01566.x
https://doi.org/10.1111/j.1469-1795.2006.00073.x
https://doi.org/10.1111/j.1600-0684.2010.00464.x
https://doi.org/10.1111/jzo.12769
https://doi.org/10.1111/mam.12173
https://doi.org/10.1111/mam.12225
https://doi.org/10.1111/mec.15437
https://doi.org/10.1111/tbed.12248
https://doi.org/10.1111/tbed.12522
https://doi.org/10.1111/tbed.12580
https://doi.org/10.1111/tbed.12833
https://doi.org/10.1111/zph.12509
https://doi.org/10.1111/zph.12540
https://doi.org/10.1111/zph.12563
https://doi.org/10.1139/z81-107
https:/ /doi.org/10.1371/journal.pcbi.1009706
https://doi.org/ 10.1371/journal.pntd.0008092
https://doi.org/10.2307/3504205
https://doi.org/10.2903/j.efsa.2015.4161
https://doi.org/10.2903/j.efsa.2017.4890
https://doi.org/10.3158/2158-5520-12.6.1
https://doi.org/10.3389/fimmu.2021.706951
https://doi.org/10.3390/v14010072
nri2939 [pii]\r10.1038/nri2939
```

**Comment by jhpoelen** [comment]
Note that ```10.2903/j.efsa.2015.4161``` is a DOI and has a similar structure as the 2738 other DOIs with valid ```10.``` prefix.

**Comment by jhpoelen** [comment]
I've included an exhaustive list of DOIs in the v0.2 corpus in the attached file. Most start with ```10.``` as expected.

[all-dois.csv](https://github.com/bat-literature/bat-literature.github.io/files/15504764/all-dois.csv)

**Comment by ajacsherman** [comment]
This will take me two days at least. Let's see if we can streamline DOI verification/correction. Looking into it...

**Comment by jhpoelen** [comment]
@ajacsherman thanks for having a look. Please do note that I noted just 46 suspicious DOIs as listed in https://github.com/bat-literature/bat-literature.github.io/issues/4#issuecomment-2140708382 . If you scan the entire list of DOIs, you might notice the differences in form (e.g., 10. notation, vs non-10. notation).

**Comment by jhpoelen** [comment]
@ajacsherman I've re-written the DOI syntax check script to include the associated Zotero record url - 

using 

```bash 
preston ls\
 --algo md5\
 --anchor hash://md5/be692b93a8edde4c4269be9e7d4ec1d7\
 --remote https://linker.bio\
 | grep hasVersion\
 | grep "items?"\
 | preston cat\
 | jq --raw-output '.[] | select(.data.DOI | length > 0  )  | [ .data.DOI, .links.alternate.href ] | @tsv' | grep -v "^10."\
 | mlr --itsvlite --omd cat
```

resulted in 

| suspicious DOI | Zotero record URL |
| --- | --- |
| https://doi.org/10.3158/2158-5520-12.6.1 | https://www.zotero.org/groups/bat_literature_project/items/LLKZXQQA |
| https://doi.org/ 10.1371/journal.pntd.0008092 | https://www.zotero.org/groups/bat_literature_project/items/TBIXMEZ6 |
| https://doi.org/10.1098/rsbl.2021.0427 | https://www.zotero.org/groups/bat_literature_project/items/AX2BJVCL |
| https://doi.org/10.3390/v14010072 | https://www.zotero.org/groups/bat_literature_project/items/J5UDBN83 |
| https:/ /doi.org/10.1371/journal.pcbi.1009706 | https://www.zotero.org/groups/bat_literature_project/items/2YYYFWNK |
| https://doi.org/10.1139/z81-107 | https://www.zotero.org/groups/bat_literature_project/items/BE8ZPHQY |
| https://doi.org/10.2307/3504205 | https://www.zotero.org/groups/bat_literature_project/items/BE6KWPH9 |
| https://doi.org/10.1111/jzo.12769 | https://www.zotero.org/groups/bat_literature_project/items/CV4THVM6 |
| https://doi.org/10.1111/zph.12563 | https://www.zotero.org/groups/bat_literature_project/items/4LIDRK8Q |
| https://doi.org/10.1111/zph.12540 | https://www.zotero.org/groups/bat_literature_project/items/7CAB2PJ5 |
| https://doi.org/10.1111/tbed.12580 | https://www.zotero.org/groups/bat_literature_project/items/CYR43UDI |
| https://doi.org/10.1111/tbed.12833 | https://www.zotero.org/groups/bat_literature_project/items/UVJ33NQ4 |
| https://doi.org/10.2903/j.efsa.2017.4890 | https://www.zotero.org/groups/bat_literature_project/items/AP43YRHP |
| https://doi.org/10.2903/j.efsa.2015.4161 | https://www.zotero.org/groups/bat_literature_project/items/FK7P8UD4 |
| https://doi.org/10.1002/pro.2541 | https://www.zotero.org/groups/bat_literature_project/items/EM3D5ZXL |
| https://doi.org/10.1111/mam.12173 | https://www.zotero.org/groups/bat_literature_project/items/47WJFRSW |
| https://doi.org/10.1002/ece3.4842 | https://www.zotero.org/groups/bat_literature_project/items/6ZT9U43D |
| https://doi.org/10.1002/(SICI)1099-145X(199907/08)10:4<311::AID-LDR362>3.0.CO;2-3 | https://www.zotero.org/groups/bat_literature_project/items/LW3WMY4R |
| https://doi.org/10.1002/rse2.195 | https://www.zotero.org/groups/bat_literature_project/items/C6UM6BA7 |
| https://doi.org/10.1046/j.0141-6707.2000.00299.x | https://www.zotero.org/groups/bat_literature_project/items/5FNF97FV |
| https://doi.org/ 10.1017/S0031182019000817 | https://www.zotero.org/groups/bat_literature_project/items/SHCAKTMI |
| https://doi.org/10.1002/ece3.5150 | https://www.zotero.org/groups/bat_literature_project/items/H7MXWJYM |
| https://doi.org/10.1111/mam.12225 | https://www.zotero.org/groups/bat_literature_project/items/723KLFAS |
| https://doi.org/10.1111/eva.12514 | https://www.zotero.org/groups/bat_literature_project/items/KU4NHBKY |
| https://doi.org/10.3389/fimmu.2021.706951 | https://www.zotero.org/groups/bat_literature_project/items/UU83B294 |
| https://doi.org/10.1111/mec.15437 | https://www.zotero.org/groups/bat_literature_project/items/Y7D7J5QM |
| arXiv:1505.02710 | https://www.zotero.org/groups/bat_literature_project/items/T5JZXMWX |
| Artn 550\\rDoi 10.1186/S13059-014-0550-8 | https://www.zotero.org/groups/bat_literature_project/items/8E6KDZXE |
| https://doi.org/10.1111/1365-2664.13619 | https://www.zotero.org/groups/bat_literature_project/items/T46CFDTJ |
| https://doi.org/10.1111/1365-2656.13166 | https://www.zotero.org/groups/bat_literature_project/items/UJXMI3CX |
| nri2939 [pii]\\r10.1038/nri2939 | https://www.zotero.org/groups/bat_literature_project/items/2WK8GVE9 |
| https://doi.org/10.1111/j.1469-1795.2006.00073.x | https://www.zotero.org/groups/bat_literature_project/items/UM24WNSY |
| https://doi.org/10.1111/zph.12509 | https://www.zotero.org/groups/bat_literature_project/items/IP257X4S |
| https://doi.org/10.1111/tbed.12522 | https://www.zotero.org/groups/bat_literature_project/items/4C7SM4R3 |
| https://doi.org/10.1111/tbed.12248 | https://www.zotero.org/groups/bat_literature_project/items/9AJVCVIE |
| https://doi.org/10.1111/j.1600-0684.2010.00464.x | https://www.zotero.org/groups/bat_literature_project/items/CQVCHDVX |
| https://doi.org/10.1111/conl.12715 | https://www.zotero.org/groups/bat_literature_project/items/6LV7DIQT |
| https://doi.org/10.1111/j.1365-2664.2005.01049.x | https://www.zotero.org/groups/bat_literature_project/items/3GT3IZ8H |
| http://dx.doi.org/10.1038/s41467-018-06779-w | https://www.zotero.org/groups/bat_literature_project/items/4XMQKTXT |
| https://doi.org/10.1111/geb.13045 | https://www.zotero.org/groups/bat_literature_project/items/JTH8K6E7 |
| https://doi.org/10.1111/1365-2435.13640 | https://www.zotero.org/groups/bat_literature_project/items/VBWGG4WY |
| https://doi.org/10.1111/j.1461-0248.2010.01566.x | https://www.zotero.org/groups/bat_literature_project/items/E4D2HGPV |
| https://doi.org/10.1002/ajp.23240 | https://www.zotero.org/groups/bat_literature_project/items/BRZA6R7D |
| https://doi.org/10.1111/conl.12389 | https://www.zotero.org/groups/bat_literature_project/items/GPIDWZ4C |
| https://doi.org/10.1111/2041-210X.12172 | https://www.zotero.org/groups/bat_literature_project/items/MF43MGN5 |

**Comment by jhpoelen** [comment]
closing this issue to make room for fresh doi review.
