### ISSUE TITLE
demonstrate how to download all the metadata / data related to a BatLit corpus

### ISSUE THREAD

**Issue by jhpoelen** [bat-literature/bat-literature.github.io#46]

**Comment by jhpoelen** [comment]
You can collect all openly accessible (meta) data associated with a batlit version using a single line:

```
preston clone --algo md5 --remote https://zenodo.org https://batlit.org/data
```

If you have a physical copy of batlit handy (like @ajacsherman does, as shown in https://jhpoelen.nl/nasbr-talk-2024-10-25/#/how-was-jorrit-able-to-access-this-paper-at-30000-ft-2), you can speed up the transfer of the corpus dramatically, because you don't have to go through rate limited web apis and internet connections.

![image](https://github.com/user-attachments/assets/559f7a97-b4e8-43ff-8a79-af5daff06103)

**Comment by jhpoelen** [comment]
If you'd only like to have the metadata associated to the batlit corpus, you can use the workflow documented on https://batlit.org .

```
preston cat --remote https://batlit.org/data hash://md5/ce1e7618f237ff56e74d51f496e811a3\
 | grep "items[?]"\
 | grep hasVersion\
 | preston cat --remote https://batlit.org/data
```

**Comment by jhpoelen** [comment]
fyi @slint

**Comment by myrmoteras** [comment]
The goal is to be able to get a CSV including the entire batlit records and in fact any community directly from Zenodo without using an external service. There should be minimal version initially, that could also be accompanied by richer version or other format such as bibtex or endnote to include into bigliographic tools.

[refs_example_donat.csv](https://github.com/user-attachments/files/18184480/refs_example_donat.csv)
[refs_example_donat.xlsx](https://github.com/user-attachments/files/18184482/refs_example_donat.xlsx)

**Comment by jhpoelen** [comment]
Ok, thanks for clarifying. Sounds like you are describing some kind of Zenodo feature that relies on the Zenodo Web API and their underlying search index. 

I am still unsure whether the existing https://batlit.org/refs.csv or https://batlit.org/zenodo/refs-on-zenodo.csv meets you needs. But perhaps this is no longer relevant given your stated constraints.

**Comment by myrmoteras** [comment]
no, the understanding is that when you upload a record you get the respective DOI / Zenodo ID back, integrate this into the upload data and with this create a CSV records.

**Comment by myrmoteras** [comment]
this is what is needed 
![image](https://github.com/user-attachments/assets/b0d23d42-d91f-48e8-9f5b-b56ea32c551c)

This bibliographic data is in Zotero, should show up in the CSV complimented with the Zenodo ID.
Aja should be able to reimport, others in their respective DB

**Comment by myrmoteras** [comment]
this is close to the CSV envisioned. thanks
Why does this include not all the records (17028 instead of about 20,600)? Does this only include the open ones?

**Comment by jhpoelen** [comment]
> this is close to the CSV envisioned. thanks

I am not sure what that means. Please be specific.

> Why does this include not all the records (17028 instead of about 20,600)? 
According to the 250MiB snapshot of the Zenodo search index as sampled through their Web API in period 2024-12-12T18:19:40/2024-12-12T21:52:36 as described by hash://md5/fe634ab84d48b6a9b58adc9e038ecd86 and published in https://github.com/bat-literature/bat-literature.github.io/tree/main/zenodo , there appear to be 17,028 Zenodo deposits that associate with content of BatLit v0.7 hash://md5/ce1e7618f237ff56e74d51f496e811a3 . 

Note, however, due to the design of Zenodo Web APIs and associated infrastructure, you'd have to re-run the snapshot constantly to make sure that the associations between the versioned batlit corpus and the dynamic Zenodo batlit community are up to date.

I would challenge you to reproduce this result. 

> Does this only include the open ones?

Yes, they include open and restricted ones.
