### ISSUE TITLE
confusing content type table on https://batlit.org 

### ISSUE THREAD

**Issue by jhpoelen** [bat-literature/bat-literature.github.io#47]
As shared by @arw36 in https://covid19taf.slack.com/archives/C011W4GPXDX/p1733962173977579?thread_ts=1733938385.640039&cid=C011W4GPXDX

![image](https://github.com/user-attachments/assets/391353e9-5afe-4951-a03e-4722bccb37b1)

**Comment by jhpoelen** [comment]
I've just added this text to the https://batlit.org page

> These types are provided by Zotero. You can find background on these contentTypes (aka item types) at https://www.zotero.org/support/kb/item_types_and_fields .

fyi @arw36

**Comment by arw36** [comment]
Thanks for linking to this. I am still confused: 

- what is an "annotation"? This is not listed in the Zotero glossary. 
- Do 4,907 do not have an associated type based on attachments minus the sum of Zotero listed types in the file? 
- I'd recommend to separate the "top-level" and the "associated content" if displaying for summary purposes.
