### ISSUE TITLE
Add zenodo workflow to documentation. 

### ISSUE THREAD

**Issue by arw36** [bat-literature/bat-literature.github.io#54]
I had to dig quiet a bit to understand the upload process to Zenodo. Suggest to link more explicitly to these functions within [preston](https://github.com/bio-guoda/preston/tree/main/preston-zenodo/src/main/java/bio/guoda/preston/zenodo) or ideally host local script in the directory. For what it's worth, would be nice to see less dependencies and file annotation so an outsider can understand the workflow of these java scripts.

**Comment by arw36** [comment]
I don't know java, so am looking at implementing via python.

**Comment by jhpoelen** [comment]
I've added zenodo workflow to the documentation on https://batlit.org .
