### ISSUE TITLE
request for review of 5 sample Zenodo records derived from Zotero batlit records

### ISSUE THREAD

**Issue by jhpoelen** [bat-literature/bat-literature.github.io#7]
@ajacsherman @myrmoteras please review sample Zenodo records derived from Zotero records below

used

```
preston track\
    --algo md5\
    "https://api.zotero.org/groups/5435545/items?start=0&limit=25"
```

to take a snapshot of a first few records in the batlit group

and 

```
preston ls --algo md5\
   | preston zotero-stream\
   --algo md5\
   --communities batlit,biosyslit\
   | preston track\
   --algo md5\
   | preston zenodo\
   --algo md5\
   --access-token [SECRET_ACCESS_TOKEN]\
   --endpoint https://sandbox.zenodo.org\
 ```

to publish the tracked Zotero records and associated pdfs to Zenodo pubs for your review

> Velazquez-Salinas, L., Naik, S., Pauszek, S. J., Peng, K.-W., Russell, S. J., & Rodriguez, L. L. (2017). Oncolytic Recombinant Vesicular Stomatitis Virus (VSV) Is Nonpathogenic and Nontransmissible in Pigs, a Natural Host of VSV. Human Gene Therapy Clinical Development, 28(2), 108–115. https://sandbox.zenodo.org/records/55817

> Aellen, V., & Brosset, A. (1968). Chiroptères du sud du Congo (Brazzaville). Revue Suisse De Zoologie., 75, 435–458. https://sandbox.zenodo.org/records/55814

> Alberico, M. S., & Velasco, E. (1991). Description of a new broad-nosed bat from Colombia. Bonner Zoologische Beiträge, 42, 237–239. https://sandbox.zenodo.org/records/55813

> Albuja V, L., Gardner, A. L., & Graves, G. R. (2005). A new species of Lonchophylla Thomas (Chiroptera: Phyllostomidae) from Ecuador. Proceedings of the Biological Society of Washington, 118(2), 442–449. https://sandbox.zenodo.org/records/55811

> Mônico, P. I., & Soto-Centeno, J. A. (2024). Phylogenetic, morphological and niche differentiation unveil new species limits for the big brown bat ( Eptesicus fuscus ). Royal Society Open Science, 11(2), 231384. https://sandbox.zenodo.org/records/55810

See also attached screenshots of Zenodo sandbox html landing page of Albuja et al. 2005 .

![Screenshot from 2024-05-16 11-34-37](https://github.com/bio-guoda/preston/assets/1084872/54b1fd53-7460-4828-b482-e61a1fe2e981)
![Screenshot from 2024-05-16 11-34-31](https://github.com/bio-guoda/preston/assets/1084872/d2ff4b48-7b3f-46ba-87e0-93fc358685f5)
![Screenshot from 2024-05-16 11-34-21](https://github.com/bio-guoda/preston/assets/1084872/323dfe32-3dda-476b-8beb-fe330d7c5b91)

_Originally posted by @jhpoelen in https://github.com/bio-guoda/preston/issues/286#issuecomment-2115702922_

**Comment by ajacsherman** [comment]
Hi Jorrit,
Looks good so far! Just a couple questions...
We found the hash/ link under URL identifiers doesn't go anywhere. Is this something you will add later? 
The doi is a Zenodo doi. Will we list others if they exist? (For example, Albuja V, L., Gardner, A. L., & Graves, G. R. (2005). A new species of Lonchophylla Thomas (Chiroptera: Phyllostomidae) from Ecuador. Proceedings of the Biological Society of Washington, 118(2), 442–449. has a doi; https://doi.org/10.2988/0006-324X(2005)118[442:ANSOLT]2.0.CO;2) Do we need to retain both?
How will we address transcription errors like "( <i>Eptesicus fuscus</i> )" in the title from Monico & Soto-Centeno, 2024.

**Comment by jhpoelen** [comment]
@ajacsherman Thanks for your response. Glad to hear things are looking good so far.

Please see below for my attempt to answering your questions - 

> We found the hash/ link under URL identifiers doesn't go anywhere. Is this something you will add later?

Some related identifiers may not work in the sandbox/ test mode we are currently using. 

Which urls in what zenodo record didn't go anywhere? 

> The doi is a Zenodo doi. Will we list others if they exist?

Yes, existing dois are listed under additional details > identifiers > DOI . 

See e.g., attached screenshot.
![image](https://github.com/bat-literature/bat-literature.github.io/assets/1084872/22174c61-777c-45e8-954d-27377497c145)

> How will we address transcription errors like "( Eptesicus fuscus )" in the title from Monico & Soto-Centeno, 2024.

You make the update in Zotero, and the correction will be included in the following release. See suggested curatorial workflows in https://bat-literature.github.io/#curation-workflow . 

Please close this issue if all questions are answered. Otherwise, please comment and help me to better understand your question.
