### ISSUE TITLE
add support for Zotero types beyond articles/attachments : books, book sections, reports etc.

### ISSUE THREAD

**Issue by jhpoelen** [bat-literature/bat-literature.github.io#8]
currently, only Zotero article types and attachments are translated into Zenodo speak.

suggest to also include book, book sections and report etc types.

**Comment by jhpoelen** [comment]
6853 attachment
   3105 journalArticle
    749 note
     94 annotation
     71 bookSection
     47 report
     46 book
     15 conferencePaper
      9 thesis
      6 webpage
      5 preprint
      3 newspaperArticle
      3 magazineArticle

**Comment by ajacsherman** [comment]
Yes, please include books, book sections, etc. as well.

**Comment by jhpoelen** [comment]
Thanks for confirming that books, book sections should be included.

I've added support for these publication types and hoping to review them as we finish up the existing review items.
